import { NextRequest, NextResponse } from 'next/server';
import type { PriceSearchQuery, PriceSearchResponse, PriceSearchResult } from '@/lib/types';

// Mock data para demonstração - Expandido com mais produtos
const mockPriceDatabase: PriceSearchResult[] = [
  // Cimento
  {
    id: '1',
    productName: 'Cimento Portland',
    brand: 'Itaú',
    model: 'CP II-Z-32',
    price: 35.50,
    quality: 'high',
    warranty: '12 meses',
    supplier: 'Materiais de Construção Silva',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.silva.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.5,
    inStock: true,
  },
  {
    id: '2',
    productName: 'Cimento Portland',
    brand: 'Votorantim',
    model: 'CP II-Z-32',
    price: 32.00,
    quality: 'medium',
    warranty: '12 meses',
    supplier: 'Construção Rápida',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.construcaorapida.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.0,
    inStock: true,
  },
  {
    id: '2a',
    productName: 'Cimento Portland',
    brand: 'Votorantim',
    model: 'CP II-Z-32',
    price: 31.00,
    quality: 'medium',
    warranty: '12 meses',
    supplier: 'Construção Rápida',
    location: { state: 'RJ', city: 'Rio de Janeiro' },
    url: 'https://www.construcaorapida.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.0,
    inStock: true,
  },
  // Tinta
  {
    id: '3',
    productName: 'Tinta Acrílica',
    brand: 'Suvinil',
    model: 'Premium',
    price: 85.00,
    quality: 'high',
    warranty: '24 meses',
    supplier: 'Tintas e Acabamentos',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.tintasacabamentos.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.8,
    inStock: true,
  },
  {
    id: '4',
    productName: 'Tinta Acrílica',
    brand: 'Coral',
    model: 'Standard',
    price: 65.00,
    quality: 'medium',
    warranty: '12 meses',
    supplier: 'Loja de Tintas Central',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.tintascentral.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.2,
    inStock: true,
  },
  // Piso Cerâmico
  {
    id: '5',
    productName: 'Piso Cerâmico',
    brand: 'Portinari',
    model: 'Retificado 60x60',
    price: 120.00,
    quality: 'high',
    warranty: '24 meses',
    supplier: 'Cerâmica Premium',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.ceramicapremium.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.7,
    inStock: true,
  },
  {
    id: '6',
    productName: 'Piso Cerâmico',
    brand: 'Brasital',
    model: 'Simples 45x45',
    price: 45.00,
    quality: 'low',
    warranty: '12 meses',
    supplier: 'Materiais Econômicos',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.materiaiseconomicos.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 3.5,
    inStock: true,
  },
  // Piso Laminado
  {
    id: '9',
    productName: 'Piso Laminado',
    brand: 'Durafloor',
    model: 'Carvalho Europeu',
    price: 95.00,
    quality: 'high',
    warranty: '10 anos',
    supplier: 'Pisos Premium',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.pisospremium.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.6,
    inStock: true,
  },
  {
    id: '10',
    productName: 'Piso Laminado',
    brand: 'Eucafloor',
    model: 'Jatobá Natural',
    price: 78.00,
    quality: 'medium',
    warranty: '5 anos',
    supplier: 'Loja de Pisos Central',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.lojapioscentral.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.3,
    inStock: true,
  },
  {
    id: '11',
    productName: 'Piso Laminado',
    brand: 'Tarkett',
    model: 'Nogueira Escura',
    price: 110.00,
    quality: 'high',
    warranty: '15 anos',
    supplier: 'Pisos Premium',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.pisospremium.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.7,
    inStock: true,
  },
  // Piso Vinílico
  {
    id: '12',
    productName: 'Piso Vinílico',
    brand: 'Durafloor',
    model: 'Madeira Rústica',
    price: 55.00,
    quality: 'medium',
    warranty: '5 anos',
    supplier: 'Pisos Econômicos',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.pisoseconomicos.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.2,
    inStock: true,
  },
  {
    id: '13',
    productName: 'Piso Vinílico',
    brand: 'Tarkett',
    model: 'Mármore Cinza',
    price: 68.00,
    quality: 'high',
    warranty: '7 anos',
    supplier: 'Pisos Premium',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.pisospremium.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.5,
    inStock: true,
  },
  {
    id: '14',
    productName: 'Piso Vinílico',
    brand: 'Eucafloor',
    model: 'Madeira Clara',
    price: 48.00,
    quality: 'low',
    warranty: '3 anos',
    supplier: 'Materiais Econômicos',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.materiaiseconomicos.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 3.8,
    inStock: true,
  },
  // Telha Cerâmica
  {
    id: '7',
    productName: 'Telha Cerâmica',
    brand: 'Brasital',
    model: 'Francesa',
    price: 2.50,
    quality: 'medium',
    warranty: '10 anos',
    supplier: 'Telhas Brasil',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.telhasbrasil.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.1,
    inStock: true,
  },
  {
    id: '8',
    productName: 'Telha Cerâmica',
    brand: 'Imiporcelana',
    model: 'Portuguesa',
    price: 3.20,
    quality: 'high',
    warranty: '15 anos',
    supplier: 'Cerâmica Premium',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.ceramicapremium.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.6,
    inStock: true,
  },
  // Gesso
  {
    id: '15',
    productName: 'Gesso',
    brand: 'Gesso Drywall',
    model: 'Placa Standard',
    price: 28.00,
    quality: 'medium',
    warranty: '12 meses',
    supplier: 'Materiais de Construção Silva',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.silva.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.3,
    inStock: true,
  },
  {
    id: '16',
    productName: 'Gesso',
    brand: 'Knauf',
    model: 'Placa Resistente',
    price: 35.00,
    quality: 'high',
    warranty: '24 meses',
    supplier: 'Construção Rápida',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.construcaorapida.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.6,
    inStock: true,
  },
  // Azulejo
  {
    id: '17',
    productName: 'Azulejo',
    brand: 'Brasital',
    model: 'Branco 20x20',
    price: 35.00,
    quality: 'medium',
    warranty: '12 meses',
    supplier: 'Materiais Econômicos',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.materiaiseconomicos.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.0,
    inStock: true,
  },
  {
    id: '18',
    productName: 'Azulejo',
    brand: 'Portinari',
    model: 'Azul Marinho 30x30',
    price: 65.00,
    quality: 'high',
    warranty: '24 meses',
    supplier: 'Cerâmica Premium',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.ceramicapremium.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.7,
    inStock: true,
  },
  // Madeira
  {
    id: '19',
    productName: 'Madeira',
    brand: 'Madeireira Silva',
    model: 'Pinus 2x4',
    price: 12.00,
    quality: 'low',
    warranty: '6 meses',
    supplier: 'Madeireira Silva',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.madeireira-silva.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 3.9,
    inStock: true,
  },
  {
    id: '20',
    productName: 'Madeira',
    brand: 'Madeireira Premium',
    model: 'Ipê 2x4',
    price: 45.00,
    quality: 'high',
    warranty: '12 meses',
    supplier: 'Madeireira Premium',
    location: { state: 'SP', city: 'São Paulo' },
    url: 'https://www.madeireira-premium.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.8,
    inStock: true,
  },
  // Produtos RJ
  {
    id: '21',
    productName: 'Cimento Portland',
    brand: 'Itaú',
    model: 'CP II-Z-32',
    price: 36.50,
    quality: 'high',
    warranty: '12 meses',
    supplier: 'Construção Rio',
    location: { state: 'RJ', city: 'Rio de Janeiro' },
    url: 'https://www.construcaoRio.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.4,
    inStock: true,
  },
  {
    id: '22',
    productName: 'Piso Laminado',
    brand: 'Durafloor',
    model: 'Carvalho Europeu',
    price: 98.00,
    quality: 'high',
    warranty: '10 anos',
    supplier: 'Pisos Rio',
    location: { state: 'RJ', city: 'Rio de Janeiro' },
    url: 'https://www.pisosrio.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.5,
    inStock: true,
  },
  {
    id: '23',
    productName: 'Piso Vinílico',
    brand: 'Tarkett',
    model: 'Mármore Cinza',
    price: 70.00,
    quality: 'high',
    warranty: '7 anos',
    supplier: 'Pisos Rio',
    location: { state: 'RJ', city: 'Rio de Janeiro' },
    url: 'https://www.pisosrio.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.4,
    inStock: true,
  },
  {
    id: '24',
    productName: 'Tinta Acrílica',
    brand: 'Suvinil',
    model: 'Premium',
    price: 87.00,
    quality: 'high',
    warranty: '24 meses',
    supplier: 'Tintas Rio',
    location: { state: 'RJ', city: 'Rio de Janeiro' },
    url: 'https://www.tintasrio.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.7,
    inStock: true,
  },
  // Produtos MG
  {
    id: '25',
    productName: 'Cimento Portland',
    brand: 'Votorantim',
    model: 'CP II-Z-32',
    price: 30.00,
    quality: 'medium',
    warranty: '12 meses',
    supplier: 'Construção Minas',
    location: { state: 'MG', city: 'Belo Horizonte' },
    url: 'https://www.construcaominas.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.1,
    inStock: true,
  },
  {
    id: '26',
    productName: 'Piso Laminado',
    brand: 'Eucafloor',
    model: 'Jatobá Natural',
    price: 75.00,
    quality: 'medium',
    warranty: '5 anos',
    supplier: 'Pisos Minas',
    location: { state: 'MG', city: 'Belo Horizonte' },
    url: 'https://www.pisosminas.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.2,
    inStock: true,
  },
  {
    id: '27',
    productName: 'Azulejo',
    brand: 'Portinari',
    model: 'Azul Marinho 30x30',
    price: 62.00,
    quality: 'high',
    warranty: '24 meses',
    supplier: 'Cerâmica Minas',
    location: { state: 'MG', city: 'Belo Horizonte' },
    url: 'https://www.ceramicaminas.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.6,
    inStock: true,
  },
  // Produtos BA
  {
    id: '28',
    productName: 'Piso Cerâmico',
    brand: 'Portinari',
    model: 'Retificado 60x60',
    price: 125.00,
    quality: 'high',
    warranty: '24 meses',
    supplier: 'Cerâmica Bahia',
    location: { state: 'BA', city: 'Salvador' },
    url: 'https://www.ceramicabahia.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.6,
    inStock: true,
  },
  {
    id: '29',
    productName: 'Piso Vinílico',
    brand: 'Durafloor',
    model: 'Madeira Rústica',
    price: 58.00,
    quality: 'medium',
    warranty: '5 anos',
    supplier: 'Pisos Bahia',
    location: { state: 'BA', city: 'Salvador' },
    url: 'https://www.pisosbahia.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.1,
    inStock: true,
  },
  {
    id: '30',
    productName: 'Tinta Acrílica',
    brand: 'Coral',
    model: 'Standard',
    price: 63.00,
    quality: 'medium',
    warranty: '12 meses',
    supplier: 'Tintas Bahia',
    location: { state: 'BA', city: 'Salvador' },
    url: 'https://www.tintasbahia.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.0,
    inStock: true,
  },
  // Produtos RS
  {
    id: '31',
    productName: 'Piso Laminado',
    brand: 'Tarkett',
    model: 'Nogueira Escura',
    price: 108.00,
    quality: 'high',
    warranty: '15 anos',
    supplier: 'Pisos Sul',
    location: { state: 'RS', city: 'Porto Alegre' },
    url: 'https://www.pisossul.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.6,
    inStock: true,
  },
  {
    id: '32',
    productName: 'Gesso',
    brand: 'Knauf',
    model: 'Placa Resistente',
    price: 33.00,
    quality: 'high',
    warranty: '24 meses',
    supplier: 'Construção Sul',
    location: { state: 'RS', city: 'Porto Alegre' },
    url: 'https://www.construcaosul.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.5,
    inStock: true,
  },
  {
    id: '33',
    productName: 'Madeira',
    brand: 'Madeireira Silva',
    model: 'Pinus 2x4',
    price: 11.00,
    quality: 'low',
    warranty: '6 meses',
    supplier: 'Madeireira Sul',
    location: { state: 'RS', city: 'Porto Alegre' },
    url: 'https://www.madeireira-sul.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 3.8,
    inStock: true,
  },
  // Produtos PR
  {
    id: '34',
    productName: 'Piso Cerâmico',
    brand: 'Brasital',
    model: 'Simples 45x45',
    price: 43.00,
    quality: 'low',
    warranty: '12 meses',
    supplier: 'Materiais Paraná',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.materiaisparana.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 3.6,
    inStock: true,
  },
  {
    id: '35',
    productName: 'Telha Cerâmica',
    brand: 'Brasital',
    model: 'Francesa',
    price: 2.40,
    quality: 'medium',
    warranty: '10 anos',
    supplier: 'Telhas Paraná',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.telhasparana.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.0,
    inStock: true,
  },
  {
    id: '36',
    productName: 'Piso Laminado',
    brand: 'Durafloor',
    model: 'Carvalho Europeu',
    price: 92.00,
    quality: 'high',
    warranty: '10 anos',
    supplier: 'Pisos Curitiba',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.pisoscuritiba.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.5,
    inStock: true,
  },
  {
    id: '37',
    productName: 'Piso Laminado',
    brand: 'Eucafloor',
    model: 'Jatobá Natural',
    price: 76.00,
    quality: 'medium',
    warranty: '5 anos',
    supplier: 'Loja Pisos Paraná',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.lojapiosparana.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.2,
    inStock: true,
  },
  {
    id: '38',
    productName: 'Piso Vinílico',
    brand: 'Tarkett',
    model: 'Mármore Cinza',
    price: 66.00,
    quality: 'high',
    warranty: '7 anos',
    supplier: 'Pisos Premium Curitiba',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.pisospremiumcuritiba.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.4,
    inStock: true,
  },
  {
    id: '39',
    productName: 'Piso Vinílico',
    brand: 'Durafloor',
    model: 'Madeira Rústica',
    price: 52.00,
    quality: 'medium',
    warranty: '5 anos',
    supplier: 'Pisos Econômicos Paraná',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.pisoseconomicospr.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.0,
    inStock: true,
  },
  {
    id: '40',
    productName: 'Cimento Portland',
    brand: 'Itaú',
    model: 'CP II-Z-32',
    price: 34.00,
    quality: 'high',
    warranty: '12 meses',
    supplier: 'Construção Paraná',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.construcaoparana.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.3,
    inStock: true,
  },
  {
    id: '41',
    productName: 'Tinta Acrílica',
    brand: 'Suvinil',
    model: 'Premium',
    price: 83.00,
    quality: 'high',
    warranty: '24 meses',
    supplier: 'Tintas Curitiba',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.tintascuritiba.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.6,
    inStock: true,
  },
  {
    id: '42',
    productName: 'Tinta Acrílica',
    brand: 'Coral',
    model: 'Standard',
    price: 64.00,
    quality: 'medium',
    warranty: '12 meses',
    supplier: 'Loja Tintas Paraná',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.lojatintaspr.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.1,
    inStock: true,
  },
  {
    id: '43',
    productName: 'Gesso',
    brand: 'Gesso Drywall',
    model: 'Placa Standard',
    price: 27.00,
    quality: 'medium',
    warranty: '12 meses',
    supplier: 'Materiais Construção Paraná',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.materiaispr.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.2,
    inStock: true,
  },
  {
    id: '44',
    productName: 'Azulejo',
    brand: 'Brasital',
    model: 'Branco 20x20',
    price: 33.00,
    quality: 'medium',
    warranty: '12 meses',
    supplier: 'Cerâmica Paraná',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.ceramicaparana.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 3.9,
    inStock: true,
  },
  {
    id: '45',
    productName: 'Azulejo',
    brand: 'Portinari',
    model: 'Azul Marinho 30x30',
    price: 61.00,
    quality: 'high',
    warranty: '24 meses',
    supplier: 'Cerâmica Premium Paraná',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.ceramicapremiumpr.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.5,
    inStock: true,
  },
  {
    id: '46',
    productName: 'Madeira',
    brand: 'Madeireira Silva',
    model: 'Pinus 2x4',
    price: 10.50,
    quality: 'low',
    warranty: '6 meses',
    supplier: 'Madeireira Paraná',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.madeireira-parana.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 3.7,
    inStock: true,
  },
  {
    id: '47',
    productName: 'Madeira',
    brand: 'Madeireira Premium',
    model: 'Ipê 2x4',
    price: 42.00,
    quality: 'high',
    warranty: '12 meses',
    supplier: 'Madeireira Premium Paraná',
    location: { state: 'PR', city: 'Curitiba' },
    url: 'https://www.madeireira-premium-pr.com.br',
    lastUpdated: new Date().toISOString(),
    rating: 4.7,
    inStock: true,
  },
];

export async function POST(request: NextRequest) {
  try {
    const query: PriceSearchQuery = await request.json();

    console.log('[Web Search] Pesquisando produtos:', query.productName);

    if (!query.productName || !query.state || !query.city) {
      return NextResponse.json(
        { error: 'Parâmetros inválidos' },
        { status: 400 }
      );
    }

    // Função para buscar por palavras-chave
    const searchTerms = query.productName.toLowerCase().split(' ').filter(t => t.length > 0);
    
    const matchesProductName = (item: PriceSearchResult) => {
      const productLower = item.productName.toLowerCase();
      const brandLower = item.brand.toLowerCase();
      const modelLower = item.model.toLowerCase();
      const fullText = `${productLower} ${brandLower} ${modelLower}`;
      return searchTerms.some(term => fullText.includes(term));
    };

    const matchesPriceRange = (item: PriceSearchResult) => {
      return (!query.minPrice || item.price >= query.minPrice) &&
             (!query.maxPrice || item.price <= query.maxPrice);
    };

    const matchesQualityFilter = (item: PriceSearchResult) => {
      return !query.quality || item.quality === query.quality;
    };

    // Primeiro: tenta encontrar na cidade e estado especificados
    let results = mockPriceDatabase.filter(item => {
      const matchesLocation = 
        item.location.state.toLowerCase() === query.state.toLowerCase() &&
        item.location.city.toLowerCase() === query.city.toLowerCase();
      
      return matchesProductName(item) && matchesLocation && matchesPriceRange(item) && matchesQualityFilter(item);
    });

    console.log(`[Web Search] Encontrados ${results.length} produtos em ${query.city}, ${query.state}`);

    // Se não encontrar na cidade, busca no estado
    if (results.length === 0) {
      console.log(`[Web Search] Nenhum resultado em ${query.city}, buscando no estado ${query.state}...`);
      results = mockPriceDatabase.filter(item => {
        const matchesState = item.location.state.toLowerCase() === query.state.toLowerCase();
        return matchesProductName(item) && matchesState && matchesPriceRange(item) && matchesQualityFilter(item);
      });
    }

    // Se ainda não encontrar, busca em todo o país
    if (results.length === 0) {
      console.log('[Web Search] Nenhum resultado no estado, buscando em todo o país...');
      results = mockPriceDatabase.filter(item => {
        return matchesProductName(item) && matchesPriceRange(item) && matchesQualityFilter(item);
      });
    }

    const prices = results.map(r => r.price);
    const averagePrice = prices.length > 0 ? prices.reduce((a, b) => a + b, 0) / prices.length : 0;
    const lowestPrice = prices.length > 0 ? Math.min(...prices) : 0;
    const highestPrice = prices.length > 0 ? Math.max(...prices) : 0;

    console.log('[Web Search] Encontrados', results.length, 'produtos');

    const response: PriceSearchResponse = {
      query,
      results,
      totalResults: results.length,
      averagePrice,
      lowestPrice,
      highestPrice,
      aiInsights: '',
    };

    return NextResponse.json(response);
  } catch (error) {
    console.error('[Web Search] Erro na pesquisa:', error);
    return NextResponse.json(
      { error: 'Erro ao pesquisar preços' },
      { status: 500 }
    );
  }
}
